// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SER_Balanza_Interno.Data;

#nullable disable

namespace SER_Balanza_Interno.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002185744_AgregarCiAUsuario")]
    partial class AgregarCiAUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SER_Balanza_Interno.Models.Analisis", b =>
                {
                    b.Property<int>("DocEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DocEntry");

                    b.Property<string>("Cancelado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cancelado");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClienteId");

                    b.Property<double?>("DCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("DCalor");

                    b.Property<double?>("Danado")
                        .HasColumnType("REAL")
                        .HasColumnName("Danado");

                    b.Property<double?>("DescWeightDCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightDCalor");

                    b.Property<double?>("DescWeightDanado")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightDanado");

                    b.Property<double?>("DescWeightEnfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightEnfermo");

                    b.Property<double?>("DescWeightHumedad")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightHumedad");

                    b.Property<double?>("DescWeightImpureza")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightImpureza");

                    b.Property<double?>("DescWeightOtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightOtroColor");

                    b.Property<double?>("DescWeightPartido")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightPartido");

                    b.Property<double?>("DescWeightVerde")
                        .HasColumnType("REAL")
                        .HasColumnName("DescWeightVerde");

                    b.Property<double?>("Desc_DCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_DCalor");

                    b.Property<double?>("Desc_Danado")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Danado");

                    b.Property<double?>("Desc_Enfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Enfermo");

                    b.Property<double?>("Desc_Humedad")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Humedad");

                    b.Property<double?>("Desc_Impureza")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Impureza");

                    b.Property<double?>("Desc_OtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_OtroColor");

                    b.Property<double?>("Desc_Partido")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Partido");

                    b.Property<double?>("Desc_Verde")
                        .HasColumnType("REAL")
                        .HasColumnName("Desc_Verde");

                    b.Property<int?>("DocNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DocNum");

                    b.Property<double?>("Enfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("Enfermo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaAct")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaAct");

                    b.Property<DateTime>("FechaDoc")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaDoc");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaReg");

                    b.Property<double?>("Humedad")
                        .HasColumnType("REAL")
                        .HasColumnName("Humedad");

                    b.Property<double?>("Impureza")
                        .HasColumnType("REAL")
                        .HasColumnName("Impureza");

                    b.Property<double?>("OtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("OtroColor");

                    b.Property<double?>("PDCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("PDCalor");

                    b.Property<double?>("PDanado")
                        .HasColumnType("REAL")
                        .HasColumnName("PDanado");

                    b.Property<double?>("PEnfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("PEnfermo");

                    b.Property<double?>("PHumedad")
                        .HasColumnType("REAL")
                        .HasColumnName("PHumedad");

                    b.Property<double?>("PImpureza")
                        .HasColumnType("REAL")
                        .HasColumnName("PImpureza");

                    b.Property<double?>("POtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("POtroColor");

                    b.Property<double?>("PPartido")
                        .HasColumnType("REAL")
                        .HasColumnName("PPartido");

                    b.Property<double?>("PVerde")
                        .HasColumnType("REAL")
                        .HasColumnName("PVerde");

                    b.Property<double?>("Partido")
                        .HasColumnType("REAL")
                        .HasColumnName("Partido");

                    b.Property<double?>("PesoHectolitrico")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoHectolitrico");

                    b.Property<int?>("PesoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PesoId");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductoId");

                    b.Property<double?>("TotalDescPeso")
                        .HasColumnType("REAL")
                        .HasColumnName("TotalDescPeso");

                    b.Property<double?>("TotalDescPorcent")
                        .HasColumnType("REAL")
                        .HasColumnName("TotalDescPorcent");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Unidad");

                    b.Property<int?>("UsuarioIdAct")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsuarioIdAct");

                    b.Property<int>("UsuarioIdReg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsuarioIdReg");

                    b.Property<double?>("Verde")
                        .HasColumnType("REAL")
                        .HasColumnName("Verde");

                    b.HasKey("DocEntry");

                    b.ToTable("Analisis");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Hacienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Abreviatura");

                    b.Property<bool?>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Direccion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Hacienda");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Marca", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_marca");

                    b.Property<string>("E")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("E");

                    b.Property<string>("F")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("F");

                    b.Property<string>("FA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FA");

                    b.Property<string>("S")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("S");

                    b.Property<string>("SD")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SD");

                    b.HasKey("id_marca");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Permiso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool?>("es_grupo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_grupo");

                    b.Property<int?>("grupo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grupo");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<double?>("Danado")
                        .HasColumnType("REAL")
                        .HasColumnName("Danado");

                    b.Property<double?>("DanadoPorCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("DanadoPorCalor");

                    b.Property<double?>("Enfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("Enfermo");

                    b.Property<double?>("FDDanado")
                        .HasColumnType("REAL")
                        .HasColumnName("FDDanado");

                    b.Property<double?>("FDDanadoPorCalor")
                        .HasColumnType("REAL")
                        .HasColumnName("FDDanadoPorCalor");

                    b.Property<double?>("FDEnfermo")
                        .HasColumnType("REAL")
                        .HasColumnName("FDEnfermo");

                    b.Property<double?>("FDHumedad")
                        .HasColumnType("REAL")
                        .HasColumnName("FDHumedad");

                    b.Property<double?>("FDImpureza")
                        .HasColumnType("REAL")
                        .HasColumnName("FDImpureza");

                    b.Property<double?>("FDOtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("FDOtroColor");

                    b.Property<double?>("FDPartido")
                        .HasColumnType("REAL")
                        .HasColumnName("FDPartido");

                    b.Property<double?>("FDVerde")
                        .HasColumnType("REAL")
                        .HasColumnName("FDVerde");

                    b.Property<double?>("FactorUO")
                        .HasColumnType("REAL")
                        .HasColumnName("FactorUO");

                    b.Property<bool?>("HabilitadoUO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HabilitadoUO");

                    b.Property<bool>("HabilitarParametro")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HabilitarParametro");

                    b.Property<double?>("Humedad")
                        .HasColumnType("REAL")
                        .HasColumnName("Humedad");

                    b.Property<double?>("Impureza")
                        .HasColumnType("REAL")
                        .HasColumnName("Impureza");

                    b.Property<double?>("OtroColor")
                        .HasColumnType("REAL")
                        .HasColumnName("OtroColor");

                    b.Property<double?>("Partido")
                        .HasColumnType("REAL")
                        .HasColumnName("Partido");

                    b.Property<string>("UnidadOpcional")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UnidadOpcional");

                    b.Property<double?>("Verde")
                        .HasColumnType("REAL")
                        .HasColumnName("Verde");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<double?>("factor_correccion")
                        .HasColumnType("REAL")
                        .HasColumnName("factor_correccion");

                    b.Property<int?>("id_producto_padre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_producto_padre");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Ci")
                        .HasColumnType("TEXT")
                        .HasColumnName("ci");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Eliminado");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Habilitado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<int?>("id_balanza")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_balanza");

                    b.Property<int?>("id_rol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Activo");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Placa");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Propietario");

                    b.Property<double?>("Tara")
                        .HasColumnType("REAL")
                        .HasColumnName("Tara");

                    b.Property<DateTime?>("TaraAdquirida")
                        .HasColumnType("TEXT")
                        .HasColumnName("TaraAdquirida");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tipo");

                    b.Property<int?>("TipoTara")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoTara");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime?>("taraExpira")
                        .HasColumnType("TEXT")
                        .HasColumnName("taraExpira");

                    b.HasKey("Id");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.balanza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Direccion");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefono");

                    b.Property<bool?>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<int?>("baudRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("baudRate");

                    b.Property<int?>("dataBits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dataBits");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("id_indicador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_indicador");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ip");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int?>("nro_balanza")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nro_balanza");

                    b.Property<int?>("parity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parity");

                    b.Property<int?>("puerto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("puerto");

                    b.Property<string>("puerto_serial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("puerto_serial");

                    b.Property<bool?>("rfid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rfid");

                    b.Property<bool?>("semaforo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semaforo");

                    b.Property<int?>("stopBits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stopBits");

                    b.Property<int>("tipo_conexion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_conexion");

                    b.HasKey("id");

                    b.ToTable("balanza");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.campania", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_usuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sigla");

                    b.Property<DateTime>("valido_desde")
                        .HasColumnType("TEXT")
                        .HasColumnName("valido_desde");

                    b.Property<DateTime>("valido_hasta")
                        .HasColumnType("TEXT")
                        .HasColumnName("valido_hasta");

                    b.HasKey("id");

                    b.ToTable("campania");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.chofer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ci");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.ToTable("chofer");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.compania", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("direccion1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion1");

                    b.Property<string>("direccion2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<byte[]>("logo")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("logo");

                    b.Property<string>("nit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("razon_social")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("razon_social");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.ToTable("compania");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.documento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdProducto");

                    b.Property<int?>("Id_balanza")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_balanza");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("id_usuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("modo_transaccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modo_transaccion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("documento");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.factor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte?>("Aud_Anulado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Aud_Anulado");

                    b.Property<DateTime?>("Aud_FechaMod")
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_FechaMod");

                    b.Property<DateTime?>("Aud_FechaReg")
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_FechaReg");

                    b.Property<string>("Aud_IpMod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_IpMod");

                    b.Property<string>("Aud_IpReg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_IpReg");

                    b.Property<string>("Aud_UsuarioMod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_UsuarioMod");

                    b.Property<string>("Aud_UsuarioReg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_UsuarioReg");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("factor");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.indicador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("cant_caracter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cant_caracter");

                    b.Property<string>("caracter_ini")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("caracter_ini");

                    b.Property<string>("comando")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("comando");

                    b.Property<int?>("longitud_dato")
                        .HasColumnType("INTEGER")
                        .HasColumnName("longitud_dato");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int?>("posicion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("posicion");

                    b.HasKey("id");

                    b.ToTable("indicador");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.log_transferencia_pesaje", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdLog");

                    b.Property<string>("BalanzaDestino")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BalanzaDestino");

                    b.Property<string>("BalanzaOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BalanzaOrigen");

                    b.Property<string>("Chofer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Chofer");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cliente");

                    b.Property<string>("DocumentoDestino")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DocumentoDestino");

                    b.Property<string>("DocumentoOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DocumentoOrigen");

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Equipo");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaHora");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaIngreso");

                    b.Property<string>("HaciendaDestino")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HaciendaDestino");

                    b.Property<string>("HaciendaOrigen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HaciendaOrigen");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("TEXT")
                        .HasColumnName("Peso");

                    b.Property<int>("PesoInKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PesoInKey");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Placa");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Producto");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Proveedor");

                    b.Property<string>("Remito")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Remito");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Resultado");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Usuario");

                    b.HasKey("IdLog");

                    b.ToTable("log_transferencia_pesaje");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.numeracion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool?>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<int?>("id_documento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_documento");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int>("numeracion_inicial")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeracion_inicial");

                    b.Property<string>("prefijo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prefijo");

                    b.Property<int>("valor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("valor");

                    b.HasKey("id");

                    b.ToTable("numeracion");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.origen_destino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<bool>("es_destino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_destino");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("origen_destino");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.permiso_rol", b =>
                {
                    b.Property<int>("id_permiso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_permiso")
                        .HasColumnOrder(0);

                    b.Property<int>("id_rol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol")
                        .HasColumnOrder(1);

                    b.HasKey("id_permiso", "id_rol");

                    b.ToTable("permiso_rol");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.peso", b =>
                {
                    b.Property<int>("NroConsec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroConsec");

                    b.Property<double>("Bruto")
                        .HasColumnType("REAL")
                        .HasColumnName("Bruto");

                    b.Property<bool?>("Credito")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Credito");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaIngreso");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("TEXT")
                        .HasColumnName("FechaSalida");

                    b.Property<int?>("Id_Hacienda")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Hacienda");

                    b.Property<int>("Id_UsuarioSal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_UsuarioSal");

                    b.Property<int?>("Id_balanza")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_balanza");

                    b.Property<int?>("Id_cliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_cliente");

                    b.Property<int?>("Id_producto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_producto");

                    b.Property<int>("Id_usuarioIng")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_usuarioIng");

                    b.Property<decimal?>("Importe")
                        .HasColumnType("TEXT")
                        .HasColumnName("Importe");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Lote");

                    b.Property<bool?>("ModeService")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModeService");

                    b.Property<double>("Neto")
                        .HasColumnType("REAL")
                        .HasColumnName("Neto");

                    b.Property<int>("NroPesaje")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroPesaje");

                    b.Property<string>("NroTicket")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NroTicket");

                    b.Property<bool>("Nulo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Nulo");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Observacion");

                    b.Property<int?>("PesoInKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PesoInKey");

                    b.Property<double?>("PesoLiquido")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoLiquido");

                    b.Property<double?>("PesoTara")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoTara");

                    b.Property<double?>("PesoUnidSec")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoUnidSec");

                    b.Property<double>("Tara")
                        .HasColumnType("REAL")
                        .HasColumnName("Tara");

                    b.Property<int?>("TipoTara")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoTara");

                    b.Property<double?>("TotalDesc")
                        .HasColumnType("REAL")
                        .HasColumnName("TotalDesc");

                    b.Property<string>("UnidadPrimaria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UnidadPrimaria");

                    b.Property<string>("cultivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cultivo");

                    b.Property<int?>("id_Chofer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Chofer");

                    b.Property<int?>("id_Proveedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Proveedor");

                    b.Property<int?>("id_Vehiculo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Vehiculo");

                    b.Property<int?>("id_campania")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_campania");

                    b.Property<int?>("id_destino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_destino");

                    b.Property<int>("id_documento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_documento");

                    b.Property<int?>("id_origen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_origen");

                    b.Property<bool>("peso_manual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peso_manual");

                    b.Property<bool?>("produccion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produccion");

                    b.Property<string>("unidadSecundaria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unidadSecundaria");

                    b.HasKey("NroConsec");

                    b.ToTable("peso");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.pesoin", b =>
                {
                    b.Property<int>("PesoInKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PesoInKey");

                    b.Property<bool?>("Credito")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Credito");

                    b.Property<DateTime>("FechaPesoIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("pesoin");

                    b.Property<int?>("Id_Hacienda")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Hacienda");

                    b.Property<int?>("Id_balanza")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_balanza");

                    b.Property<int?>("Id_cliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_cliente");

                    b.Property<int?>("Id_producto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_producto");

                    b.Property<decimal?>("Importe")
                        .HasColumnType("TEXT")
                        .HasColumnName("Importe");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Lote");

                    b.Property<bool?>("ModeService")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ModeService");

                    b.Property<int>("NroPesaje")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NroPesaje");

                    b.Property<string>("NroTicket")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NroTicket");

                    b.Property<double?>("PesoUnidSec")
                        .HasColumnType("REAL")
                        .HasColumnName("PesoUnidSec");

                    b.Property<string>("cultivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cultivo");

                    b.Property<int?>("id_Chofer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Chofer");

                    b.Property<int?>("id_Proveedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Proveedor");

                    b.Property<int?>("id_Vehiculo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_Vehiculo");

                    b.Property<int?>("id_campania")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_campania");

                    b.Property<int?>("id_destino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_destino");

                    b.Property<int?>("id_documento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_documento");

                    b.Property<int?>("id_origen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_origen");

                    b.Property<int>("id_usuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("notas")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notas");

                    b.Property<double>("peso")
                        .HasColumnType("REAL")
                        .HasColumnName("peso");

                    b.Property<bool>("peso_manual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peso_manual");

                    b.Property<bool?>("produccion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produccion");

                    b.Property<string>("unidad_primaria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unidad_primaria");

                    b.Property<string>("unidad_secundaria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unidad_secundaria");

                    b.HasKey("PesoInKey");

                    b.ToTable("pesoin");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.prod_fac_rank", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<int>("idProducto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProducto")
                        .HasColumnOrder(1);

                    b.Property<int>("idfactor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idfactor")
                        .HasColumnOrder(2);

                    b.Property<byte?>("Aud_Anulado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Aud_Anulado");

                    b.Property<DateTime?>("Aud_FechaMod")
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_FechaMod");

                    b.Property<DateTime?>("Aud_FechaReg")
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_FechaReg");

                    b.Property<string>("Aud_IpMod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_IpMod");

                    b.Property<string>("Aud_IpReg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_IpReg");

                    b.Property<string>("Aud_UsuarioMod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_UsuarioMod");

                    b.Property<string>("Aud_UsuarioReg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Aud_UsuarioReg");

                    b.Property<double?>("discount")
                        .HasColumnType("REAL")
                        .HasColumnName("discount");

                    b.Property<double?>("rank_from")
                        .HasColumnType("REAL")
                        .HasColumnName("rank_from");

                    b.Property<double?>("rank_to")
                        .HasColumnType("REAL")
                        .HasColumnName("rank_to");

                    b.HasKey("id", "idProducto", "idfactor");

                    b.ToTable("prod_fac_rank");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<bool>("eliminado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado");

                    b.HasKey("Id");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("SER_Balanza_Interno.Models.socio_negocio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("contacto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contacto");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion");

                    b.Property<bool>("es_cliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_cliente");

                    b.Property<bool>("es_proveedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_proveedor");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.ToTable("socio_negocio");
                });
#pragma warning restore 612, 618
        }
    }
}
